#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill --randomize ~/.wallpapers/* &

#this should be done by default
bspc rule -a Zathura state=tiled

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          0
bspc config top_padding         0

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config history_aware_focus         true
